/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pilote.interfacesGraphiques;

import java.awt.Color;
import javax.swing.*;
import pilote.model.*;
/**
 *
 * @author install
 */
public class FramePilote extends javax.swing.JFrame {

    /**
     * Creates new form FramePilote
     */
    public FramePilote() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tableAvion = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableAvion.setModel(new pilote.model.ModelTablePilote());
        jScrollPane2.setViewportView(tableAvion);
        tableAvion.setDefaultRenderer(String.class, new RenduTablePilote());
        tableAvion.setDefaultRenderer (Boolean.class, new RenduCheck());
        tableAvion.getColumn("Action").setCellEditor(new EditeurBoutonTable(new JCheckBox()));
        tableAvion.getColumn("Couleur").setCellEditor(new ColorCellEditor());
        tableAvion.setDefaultRenderer(Color.class, new ColorCellRenderer());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableAvion;
    // End of variables declaration//GEN-END:variables
}
